#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
echo ""
echo "  WILLHABEN WATCHER - Chrome telepítés"
echo "  ====================================="
echo ""
echo "  1. Megnyílik a Chrome + a mappa"
echo "  2. Fejlesztői mód → BE"
echo "  3. Kicsomagolt elemek betöltése"
echo "  4. Válaszd ki: Willhaben-Watcher-Chrome mappa"
echo ""
open -a "Google Chrome" "chrome://extensions/" 2>/dev/null || open "chrome://extensions/"
open "$DIR"
read -p "Nyomj Entert ha kész..."
