-- 10× KB-GG-BG2-00002 klónozása: csak geraetenummer változik (00003–00012).
-- Futtatás: Supabase SQL Editor (production: duvzbcxsfzeqjnvohifm)

insert into public.maschines (
  id,
  created_at,
  serial_nummer,
  baujahr,
  depot,
  qr_code,
  kep,
  stundenzahlerstand,
  tpg_heben_technik_7_8_gultig_bis,
  elektro_ove_e8701_e8001_gultig_bis,
  intern_8_11_gultig_bis,
  paragraf_57a_gultig_bis,
  kennzeichen,
  std_zahler_getauscht_am,
  stundenzahlerstand_alt,
  letztes_service_am,
  letztes_service_von,
  frostschutz_gepruft_am,
  schadensmeldung_status,
  beschreibung,
  subgroup,
  machine_tab_data,
  bezeichnung,
  status,
  prufung,
  geraetenummer,
  engine_type,
  engine_number,
  engine_power_kw,
  emission_standard,
  net_weight,
  total_width,
  total_height,
  total_length,
  engine_oil_type,
  engine_oil_capacity,
  hydraulic_oil_type,
  hydraulic_oil_capacity,
  arbeitsstunden
)
select
  gen_random_uuid(),
  now(),
  src.serial_nummer,
  src.baujahr,
  src.depot,
  src.qr_code,
  src.kep,
  src.stundenzahlerstand,
  src.tpg_heben_technik_7_8_gultig_bis,
  src.elektro_ove_e8701_e8001_gultig_bis,
  src.intern_8_11_gultig_bis,
  src.paragraf_57a_gultig_bis,
  src.kennzeichen,
  src.std_zahler_getauscht_am,
  src.stundenzahlerstand_alt,
  src.letztes_service_am,
  src.letztes_service_von,
  src.frostschutz_gepruft_am,
  src.schadensmeldung_status,
  src.beschreibung,
  src.subgroup,
  src.machine_tab_data,
  src.bezeichnung,
  src.status,
  src.prufung,
  v.geraetenummer,
  src.engine_type,
  src.engine_number,
  src.engine_power_kw,
  src.emission_standard,
  src.net_weight,
  src.total_width,
  src.total_height,
  src.total_length,
  src.engine_oil_type,
  src.engine_oil_capacity,
  src.hydraulic_oil_type,
  src.hydraulic_oil_capacity,
  src.arbeitsstunden
from public.maschines src
cross join (
  values
    ('KB-GG-BG2-00003'),
    ('KB-GG-BG2-00004'),
    ('KB-GG-BG2-00005'),
    ('KB-GG-BG2-00006'),
    ('KB-GG-BG2-00007'),
    ('KB-GG-BG2-00008'),
    ('KB-GG-BG2-00009'),
    ('KB-GG-BG2-00010'),
    ('KB-GG-BG2-00011'),
    ('KB-GG-BG2-00012')
) as v(geraetenummer)
where src.geraetenummer = 'KB-GG-BG2-00002'
  and not exists (
    select 1
    from public.maschines existing
    where existing.geraetenummer = v.geraetenummer
  );
