export type LagerTeil = {
  id: string;
  created_at: string;
  updated_at?: string;
  artikelnummer?: string | null;
  herstellernummer: string;
  bezeichnung?: string | null;
  bild?: string | null;
  produktgruppe?: string | null;
  lieferant?: string | null;
  lagerort?: string | null;
  lagerplatz?: string | null;
  lagerstand: number;
  menge_min?: number | null;
  menge_max?: number | null;
  listenpreis_netto?: number | null;
  listenpreis_brutto?: number | null;
  verkaufspreis?: number | null;
  bestellstatus?: string | null;
  last_inventur_at?: string | null;
  inventur_entwurf?: number | null;
  inventur_entwurf_at?: string | null;
  inventur_entwurf_by?: string | null;
};
